site_name: fengsha_prep
theme:
  name: material
repo_url: https://github.com/bbakernoaa/fengsha_prep
nav:
  - Home: index.md
  - User Guide:
    - Data Downloaders: user_guide/data_downloaders.md
    - Pipelines: user_guide/pipelines.md
  - API Reference: api_reference.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
